services:
  - type: web
    name: route-optima-backend-engine
    runtime: docker
    repo: https://github.com/Haridev-AV/logistics-engine
    plan: starter
    region: oregon 
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: route-optima-prod-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: route-optima-prod-cache
          property: connectionString
      - key: RABBITMQ_URL
        sync: false 
      - key: JWT_SECRET
        generateValue: true 
      - key: LOCATIONIQ_API_KEY
        sync: false