spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
app:
  api:
    location-iq-key: ${LOCATION_IQ_KEY}
    weather-api-key: ${WEATHER_API_KEY}
  url:
    weather: https://api.openweathermap.org/data/2.5/weather
    location-iq: https://us1.locationiq.com/v1/search.php

